version: "3.8"

services:
  # 1. PostgreSQL + TimescaleDB (時序資料庫)
  timescaledb:
    image: timescale/timescaledb:2.25.2-pg16
    container_name: iot-postgres
    environment:
      POSTGRES_USER: iot_admin
      POSTGRES_PASSWORD: poc_password
      POSTGRES_DB: iot_poc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot_admin -d iot_poc"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 2. Redis (熱點資料與緩存)
  redis:
    image: redis:7-alpine
    container_name: iot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 3. Mosquitto (MQTT Broker)
  mosquitto:
    image: eclipse-mosquitto:2.1.2
    container_name: iot-mqtt
    ports:
      - "1883:1883"
      - "9001:9001" # WebSockets 通訊埠 (如果未來前端有需要)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource # 自動安裝 Redis 插件
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - timescaledb
      - redis

# 宣告永久保存的資料卷，即使容器砍掉重建，資料也還在
volumes:
  pg_data:
  redis_data:
  mosquitto_data:
  mosquitto_log:
  grafana-storage:
